### ISSUE TITLE
Use Faker for data generation

### ISSUE THREAD

**Issue by real34** [sizuhiko/Fabricate#14]
Is it planned to use https://github.com/fzaninotto/Faker for data generation? The goal would be to have a more coherent set of data.

Any help needed with this?

**Comment by sizuhiko** [comment]
I update Fabricate to v2 for using some ORM or Frameworks.
Now, supported framework is CakePHP3.
Check it.
[FabricateContext::faker()](https://github.com/sizuhiko/Fabricate#faker-1)
[CakePHP3 Fabricate Adaptor](https://github.com/sizuhiko/cakephp-fabricate-adaptor)
